nodejs:
  aadIdentityName: juror-digital
  readinessPath: '/'
  livenessPath: '/'
  environment:
    API_ENDPOINT: http://moj-reverse-proxy-nodejs/api/v1/
    PORT: 3000
    USE_AUTH: false
    NODE_ENV: development
  ingressSessionAffinity:
    enabled: true
    sessionCookieName: affinity
  disableTraefikTls: true
  keyVaults:
    juror-digital-vault:
      secrets:
        - public-sessionSecret
        - public-jwtKey
        - public-jwtNoAuthKey
        - public-jwtKeyBureau
        - public-jwtTTL
    sessionCookieName: affinity