nodejs:
  aadIdentityName: met-schema
  readinessPath: '/'
  livenessPath: '/'
  startupPath: '/'
  environment:
    holdercleanuptask_job_cron: 0 0,30 * * * ? 
    wait_time_retry: 3000
    persist_message_audit_content_for_non_ui_flow: false
    message_audit_suppression: OFF
    gateway_connection_timeout: 720000
    gateway_receive_timeout: 720000
    soapgateway_responses_max_concurrent_processed: 20
    msgListener_concurrentConsumers: 1
    msgListener_maxConcurrentConsumers: 5
    msgListener_idleConsumerLimit: 2
    msgListener_idleTaskExecutionLimit: 10
    msgListener_cacheLevel: 3
    throttling_timeDelay: 2000
    throttling_maxThreads: 7
    throttling_enableThrottling: Y
    das_message_debug_messageSizeLimit: 50000
    xml_charEncoding: UTF-8
    das_connection_timeout: 720000
    das_receive_timeout: 720000
    updates_fixedRate_in_milliseconds: 60000
    dac_key_expire_time_seconds: 1800
    dac_number_of_instances: 6
    dac_key_allocation_fixedRate_in_milliseconds: 600000
    confiscation_schemas: 110,45,97,116,66,109
    maintenance_schemas: 111,67,44
  ingressSessionAffinity:
    enabled: true
    sessionCookieName: affinity
  disableTraefikTls: true
  keyVaults:
    libragob-kv:
      secrets:
        - db-connection-url-ThemisGatewayDS
        - db-connection-url-ThemisDacDS
        - db-connection-url-dasDS
        - db-connection-url-confDS
        - db-connection-url-finesDS
        - db-connection-url-maintenanceDS
        - db-connection-url-ThemisJmsDS