name: dotnet4.8
apiVersion: v2
version: 0.1.3
appVersion: "1.0.0"
description: Dot net 4.8 App
dependencies:
  - name: java
    version: 3.8.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
