replicas: 1

image:
  repository: hmctspublic.azurecr.io/hmcts/vsts-agent
  tag: v0.1
  pullPolicy: Always

resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #   limits:
    #     cpu: 1
    #     memory: 1Gi
    #   requests:
    #     cpu: 1
    #     memory: 1Gi

cleanRun: false

aadIdentityName: aks-pod-identity-mi

keyvault: ss-vault-sbox

azureDevOpsUrl: https://dev.azure.com/hmcts

azureDevOpsPool: hmcts-ss-sandbox

env: {}

extraEnv: {}
