replicas: 1

image:
  repository: hmctspublic.azurecr.io/hmcts/vsts-agent
  tag: db7stq
  pullPolicy: Always

resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #   limits:
    #     cpu: 1
    #     memory: 1Gi
    #   requests:
    #     cpu: 1
    #     memory: 1Gi

cleanRun: false

aadIdentity:
  name: ""
  type: ""
  resourceId: ""
  clientId: ""

keyVaults:
- name: {}
  resourceGroup: ""
  subscriptionId:  ""
  tenantId: ""
  secrets: ""

azureDevOps:
  url: ""
  pool: ""
  agentName: ""

env: {}

extraEnv: {}

volumes: {}

