name: chart-azure-devops-agent pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - charts/azure-devops-agent/*
  drafts: false
  
resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: azure-devops-agent
      chartReleaseName: chart-azure-devops-agent-ci-test
      chartNamespace: chart-tests
      chartPath: charts/azure-devops-agent/
      helmInstallTimeout: "500"
      valuesFile: "charts/azure-devops-agent/ci-values.yaml"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: azure-devops-agent
      chartReleaseName: chart-azure-devops-agent
      chartNamespace: chart-tests
      chartPath: charts/azure-devops-agent/