replicas: 1

image:
  repository: hmctspublic.azurecr.io/hmcts/vsts-agent
  tag: db7stq
  pullPolicy: Always

cleanRun: false

aadIdentityName: rpe

keyVaults:
- name: cftapps-dev
  resourceGroup: "core-infra-dev-rg"
  subscriptionId:  "8b6ea922-0862-443e-af15-6056e1c9b9a4"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  secrets:
  - azpToken

azureDevOpsUrl: https://dev.azure.com/hmcts

azureDevOpsPool: hmcts-ss-sandbox

azureDevOpsAgentName: shared-services-aks-agent-citest

env: {}

extraEnv: {}

volumes: {}

