replicas: 1

image:
  repository: hmctspublic.azurecr.io/hmcts/vsts-agent
  tag: db7stq
  pullPolicy: Always

cleanRun: false

aadIdentityName: aks-pod-identity-mi

keyVaults:
- name: ss-vault-sbox
  resourceGroup: "infra-resource-group"
  subscriptionId:  "a8140a9e-f1b0-481f-a4de-09e2ee23f7ab"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  secrets:
  - azpToken

azureDevOpsUrl: https://dev.azure.com/hmcts

azureDevOpsPool: hmcts-ss-sandbox

azureDevOpsAgentName: shared-services-aks-agent

env: {}

extraEnv: {}

volumes: {}

