replicas: 1

image:
  repository: hmctspublic.azurecr.io/hmcts/vsts-agent
  tag: db87ga
  pullPolicy: Always

cleanRun: false

aadIdentity:
  name: azure-devops-agent
  type: 0
  resourceId: /subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/resourceGroups/managed-identities-aat-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rpe-shared-aat-mi
  clientId: e9058f82-85a9-44f3-b717-848d1db8b0b9

keyVaults:
- name: cftapps-dev
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  secrets:
  - azure-devops-agent-token

azureDevOps:
  url: https://dev.azure.com/hmcts
  pool: hmcts-ss-sandbox
  agentName: shared-services-aks-agent-citest

env: {}

extraEnv: {}

volumes: {}

