nodejs:
  aadIdentityName: juror-digital
  readinessPath: '/'
  livenessPath: '/'
  environment:
    API_ENDPOINT: http://moj-nle-reverse-proxy/api/v1/
    PORT: 3000
    USE_AUTH: false
    NODE_ENV: development
    SMARTSURVEY_API_ENDPOINT: https://api.smartsurvey.io/v1/surveys/
    SMARTSURVEY_ID_V1: 301219
    SMARTSURVEY_ID_V2: 652997
    SMARTSURVEY_EXPORT_V1: "Dashboard Export"
    SMARTSURVEY_EXPORT_V2: "Dashboard Export"
  ingressSessionAffinity:
    enabled: true
    sessionCookieName: affinity
  keyVaults:
    juror-digital-vault:
      secrets:
        - bureau-sessionSecret
        - bureau-jwtKey
        - bureau-smartSurveyToken
        - bureau-smartSurveyTokenSecret
        - bureau-jwtNoAuthKey
        - bureau-jwtTTL
