---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-devops-agent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "azure-devops-agent.name" . }}
    app: {{ include "azure-devops-agent.name" . }}
    helm.sh/chart: {{ include "azure-devops-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.aadIdentityName }}
    aadpodidbinding: {{ .Values.aadIdentityName }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "azure-devops-agent.name" . }}
      app.kubernetes.io/name: {{ include "azure-devops-agent.name" . }}
      {{- if .Values.aadIdentityName }}
      aadpodidbinding: {{ .Values.aadIdentityName }}
      {{- end }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "azure-devops-agent.name" . }}
        app.kubernetes.io/name: {{ include "azure-devops-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.aadIdentityName }}
        aadpodidbinding: {{ .Values.aadIdentityName }}
        {{- end }}
    spec:
      {{- $aadIdentityName := .Values.aadIdentityName }}
      volumes:
      {{- range $.Values.keyvaults}}
      - name: {{ .name }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ $aadIdentityName }}-podid
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azure-devops-agent-secret
                key: azpToken
          {{- range $key, $value := $.Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
         {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
         {{- end }}
        volumeMounts:
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 10 }}
{{ end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
