{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-agent-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  azpToken: {{ .Values.azpToken }}
{{ end }}