nodejs:
  readinessPath: '/'
  livenessPath: '/'
  environment:
    API_ENDPOINT: http://moj-nle-reverse-proxy/api/v1/
    PORT: 80
    USE_AUTH: false
    NODE_ENV: development
  ingressSessionAffinity:
    enabled: true
    sessionCookieName: affinity
