---
apiVersion: "aadpodIdentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ include "azure-devops-agent.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  azureIdentity: aks-pod-identity-mi  # binding to existing admin-namespaced identity
  selector: aks-pod-identity-mi