apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ include "azure-devops-agent.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  azureIdentity: {{ .Values.aadIdentityName }} # binding to existing admin-namespaced identity
  selector: {{ .Values.aadIdentityName }}